export interface Service {
  slug: string
  title: string
  shortTitle: string
  description: string
  longDescription: string
  keywords: string[]
  icon: string
  benefits: string[]
  process: { step: string; desc: string }[]
  faq: { q: string; a: string }[]
  category: 'kurumsal' | 'ozel' | 'endustri'
}

export const services: Service[] = [
  /* ─── KURUMSAL ─────────────────────────────────────────────── */
  {
    slug: 'ofis-temizligi',
    title: 'Ofis Temizliği İstanbul',
    shortTitle: 'Ofis Temizliği',
    description: 'İstanbul\'da profesyonel ofis ve iş yeri temizliği. Günlük, haftalık veya aylık programlarla çalışanlarınıza hijyenik bir ortam sunuyoruz.',
    longDescription: 'Profesyonel ofis temizliği hizmetimiz, iş yerinizin her köşesini hijyenik ve düzenli tutmanızı sağlar. Mesai saatleri dışında yapılan temizlik ile iş akışınız hiç sekteye uğramaz.',
    keywords: ['ofis temizliği istanbul', 'iş yeri temizliği', 'kurumsal ofis temizliği', 'ofis temizlik şirketi istanbul'],
    icon: 'building',
    category: 'kurumsal',
    benefits: [
      'Esnek program seçenekleri (günlük, haftalık, aylık)',
      'Eğitimli ve deneyimli personel',
      'Çevre dostu temizlik ürünleri',
      'Sigortalı ve güvenilir hizmet',
      'Gece veya mesai saati dışı temizlik imkânı',
      'Tüm İstanbul ilçelerinde aktif hizmet',
    ],
    process: [
      { step: 'Ücretsiz Keşif', desc: 'Ofisinizi yerinde inceleyip ihtiyaçlarınızı belirliyoruz.' },
      { step: 'Özel Plan', desc: 'Size özel temizlik programı ve fiyat teklifi hazırlıyoruz.' },
      { step: 'Profesyonel Uygulama', desc: 'Deneyimli ekibimiz titizlikle temizlik yapıyor.' },
      { step: 'Kalite Kontrolü', desc: 'Her temizlik sonrası kalite kontrol yapılıyor.' },
    ],
    faq: [
      { q: 'Ofis temizliği ne sıklıkla yapılmalıdır?', a: 'Ofis büyüklüğüne ve çalışan sayısına göre günlük, 3 günde bir veya haftalık temizlik önerilir.' },
      { q: 'Temizlik hangi saatlerde yapılıyor?', a: 'Müşterilerin tercihine göre mesai saatleri dışında veya gece temizlik yapabiliyoruz.' },
      { q: 'Temizlik ürünleri güvenli mi?', a: 'Çevre dostu ve insan sağlığına zarar vermeyen sertifikalı temizlik ürünleri kullanıyoruz.' },
    ],
  },
  {
    slug: 'avm-temizligi',
    title: 'AVM Temizliği İstanbul',
    shortTitle: 'AVM Temizliği',
    description: 'İstanbul\'da alışveriş merkezi ve AVM temizliği. Ortak alanlar, mağazalar, yeme-içme katları ve WC alanları için 7/24 profesyonel temizlik hizmeti.',
    longDescription: 'Alışveriş merkezleri, yüksek ziyaretçi trafiği nedeniyle sürekli ve profesyonel temizlik gerektiren karmaşık yapılardır. Giriş ve çıkış alanları, yürüyen merdivenler, gıda katları, ortak tuvaletler ve mağaza önleri için özel ekipmanlarımız ve uzman personelimizle kesintisiz temizlik hizmeti sunuyoruz.',
    keywords: ['avm temizliği istanbul', 'alışveriş merkezi temizliği', 'avm temizlik şirketi', 'plaza temizliği istanbul'],
    icon: 'store',
    category: 'kurumsal',
    benefits: [
      'Yoğun trafik alanları için özel ekipman',
      'Yürüyen merdiven ve asansör temizliği',
      'Gıda katı ve restoran alanı hijyeni',
      'WC ve soyunma kabinleri temizliği',
      '7/24 acil müdahale hizmeti',
      'Görünmez temizlik prensibi (misafir varlığında)',
    ],
    process: [
      { step: 'Saha Analizi', desc: 'AVM planı ve yoğunluk saatleri incelenerek temizlik planı oluşturuluyor.' },
      { step: 'Ekip Koordinasyonu', desc: 'Her bölüm için uzman ekip ataması yapılıyor.' },
      { step: 'Kesintisiz Hizmet', desc: 'Misafir varlığında sessiz ve etkili temizlik uygulanıyor.' },
      { step: 'Süpervizör Denetimi', desc: 'Tüm alanlar anlık denetlenerek kalite güvencesi sağlanıyor.' },
    ],
    faq: [
      { q: 'AVM açıkken temizlik yapılabilir mi?', a: 'Evet, misafir konforunu bozmayan yöntemler ve sessiz ekipmanlarla açık saatlerde temizlik yapıyoruz.' },
      { q: 'Gece temizliği de yapıyor musunuz?', a: 'Evet, kapanış sonrası yoğun temizlik ve zemin cilalama gibi işlemleri gece gerçekleştiriyoruz.' },
      { q: 'Hangi İstanbul AVM\'lerine hizmet veriyorsunuz?', a: 'Avrupa ve Anadolu Yakası\'ndaki tüm büyük ve küçük alışveriş merkezlerine hizmet verme kapasitesindeyiz.' },
    ],
  },
  {
    slug: 'hastane-klinik-temizligi',
    title: 'Hastane ve Klinik Temizliği İstanbul',
    shortTitle: 'Hastane Temizliği',
    description: 'İstanbul\'da hastane, klinik, diş kliniği ve sağlık tesisi temizliği. Enfeksiyon kontrolüne uygun protokollerle steril ve hijyenik ortam sağlanması.',
    longDescription: 'Sağlık tesislerinde temizlik, hasta güvenliği açısından son derece kritik bir öneme sahiptir. Hastane enfeksiyon kontrol standartlarına uygun kimyasallar, HEPA filtreli ekipmanlar ve özel eğitimli personelimizle hastaneler, klinikler, diş muayenehaneleri ve laboratuvarlar için hijyenik ortam sağlıyoruz.',
    keywords: ['hastane temizliği istanbul', 'klinik temizliği', 'sağlık tesisi temizliği', 'tıbbi alan temizliği istanbul'],
    icon: 'hospital',
    category: 'kurumsal',
    benefits: [
      'Enfeksiyon kontrol protokollerine tam uyum',
      'Hastane onaylı dezenfektan kullanımı',
      'HEPA filtreli vakum sistemleri',
      'Bölge bazlı renk kodlu temizlik sistemi',
      'Gizlilik ve hasta mahremiyetine saygı',
      'Acil temizlik müdahalesi kapasitesi',
    ],
    process: [
      { step: 'Risk Değerlendirmesi', desc: 'Tesisin kirlilik riski haritası çıkarılıyor.' },
      { step: 'Protokol Hazırlama', desc: 'Enfeksiyon kontrol standartlarına uygun temizlik planı.' },
      { step: 'Uygulama', desc: 'Eğitimli personel bölge bazlı steril temizlik yapıyor.' },
      { step: 'Dokümantasyon', desc: 'Her temizlik kayıt altına alınıp rapora bağlanıyor.' },
    ],
    faq: [
      { q: 'Personelin hastane temizliğine özel eğitimi var mı?', a: 'Evet, tüm personel enfeksiyon kontrolü, kimyasal güvenlik ve hastane protokolleri konusunda eğitim almıştır.' },
      { q: 'Kullanılan kimyasallar sağlığa zararlı mı?', a: 'Hayır. Hastane sınıfı, Sağlık Bakanlığı onaylı dezenfektanlar kullanıyoruz.' },
      { q: 'Muayene odası ve ameliyathane temizliği yapıyor musunuz?', a: 'Evet, steril ortam gerektiren tüm alanlar dahil kapsamlı sağlık tesisi temizliği sunuyoruz.' },
    ],
  },
  {
    slug: 'okul-egitim-temizligi',
    title: 'Okul ve Eğitim Kurumu Temizliği İstanbul',
    shortTitle: 'Okul Temizliği',
    description: 'İstanbul\'da okul, dershane, üniversite ve eğitim kurumu temizliği. Sınıflar, koridorlar, tuvaletler ve yemekhaneler için çocuk güvenli ürünlerle profesyonel temizlik.',
    longDescription: 'Okullarda temizlik ve hijyen, öğrencilerin sağlığı ve başarısı için doğrudan etkilidir. Çocuklara güvenli, parfümsüz ve alerjik olmayan temizlik ürünleri kullanarak sınıflar, koridorlar, laboratuvarlar, tuvaletler ve yemekhaneler için kapsamlı temizlik hizmeti sunuyoruz.',
    keywords: ['okul temizliği istanbul', 'dershane temizliği', 'eğitim kurumu temizliği', 'okul temizlik şirketi istanbul'],
    icon: 'school',
    category: 'kurumsal',
    benefits: [
      'Çocuklara güvenli, alerjisiz ürünler',
      'Ders saatleri dışında esnek program',
      'Sınıf, laboratuvar ve kütüphane temizliği',
      'Tuvalet ve soyunma odası dezenfeksiyonu',
      'Yemekhane ve mutfak hijyeni',
      'Mevsimsel derin temizlik paketleri',
    ],
    process: [
      { step: 'Okul Turları', desc: 'Tüm bölümler incelenerek risk alanları belirleniyor.' },
      { step: 'Güvenli Ürün Seçimi', desc: 'Çocuklara uygun onaylı ürünler seçiliyor.' },
      { step: 'Program Hazırlama', desc: 'Ders saatlerine göre müfredat uyumlu temizlik takvimi.' },
      { step: 'Düzenli Uygulama', desc: 'Sözleşmeli düzenli temizlik hizmeti sunuluyor.' },
    ],
    faq: [
      { q: 'Okullar tatildeyken de temizlik yapılabilir mi?', a: 'Evet, yaz tatili ve sömestr dönemlerinde derin temizlik ve bakım hizmetleri sunuyoruz.' },
      { q: 'Yemekhane temizliği kapsamında mı?', a: 'Evet, gıda güvenliği standartlarına uygun mutfak ve yemekhane temizliği de yapıyoruz.' },
      { q: 'Dezenfeksiyon sertifikası veriyor musunuz?', a: 'Evet, her temizlik sonrasında dezenfeksiyon belgesi sunabiliyoruz.' },
    ],
  },
  {
    slug: 'showroom-temizligi',
    title: 'Showroom Temizliği İstanbul',
    shortTitle: 'Showroom Temizliği',
    description: 'İstanbul\'da showroom, teşhir salonu, otomotiv galerisi ve mağaza temizliği. Markanızın prestijini yansıtan kusursuz temizlik hizmeti.',
    longDescription: 'Showroom ve teşhir alanlarında temizlik, marka imajının ayrılmaz bir parçasıdır. Otomobil galerileri, mobilya showroomları, elektronik mağazaları ve lüks perakende mekanlar için zemin parlatma, cam ve vitrin temizliği, ürün sergileme alanı bakımı dahil kapsamlı showroom temizliği sunuyoruz.',
    keywords: ['showroom temizliği istanbul', 'teşhir salonu temizliği', 'galeri temizliği', 'mağaza temizliği istanbul'],
    icon: 'store',
    category: 'kurumsal',
    benefits: [
      'Marka standartlarına uygun temizlik',
      'Zemin parlatma ve bakımı',
      'Vitrin ve cam temizliği',
      'Ürün sergileme rafları detay temizliği',
      'Açılış öncesi hazırlık temizliği',
      'Mağaza içi koku yönetimi',
    ],
    process: [
      { step: 'Marka Brief', desc: 'Markanızın temizlik standartları ve hassasiyetleri belirleniyor.' },
      { step: 'Özel Program', desc: 'Mesai saatlerine ve etkinliklere göre program oluşturuluyor.' },
      { step: 'Hassas Temizlik', desc: 'Ürünlere zarar vermeden sergi alanları temizleniyor.' },
      { step: 'Görsel Kontrol', desc: 'Teslim öncesi görsel mükemmellik denetimi yapılıyor.' },
    ],
    faq: [
      { q: 'Açılış öncesi acil showroom temizliği yapıyor musunuz?', a: 'Evet, büyük açılışlar ve etkinlikler öncesi öncelikli temizlik hizmetimiz mevcuttur.' },
      { q: 'Otomobil galerisine hizmet veriyor musunuz?', a: 'Evet, araç sergileme alanları, yağlı zemin ve çalışma alanları dahil galeri temizliği yapıyoruz.' },
      { q: 'Markanın özel temizlik ürünlerini kullanabilir misiniz?', a: 'Evet, markanızın belirlediği ürünlerle de hizmet verebiliyoruz.' },
    ],
  },
  /* ─── ÖZEL / BİREYSEL ──────────────────────────────────────── */
  {
    slug: 'konut-temizligi',
    title: 'Konut Temizliği İstanbul',
    shortTitle: 'Konut Temizliği',
    description: 'İstanbul\'da ev ve konut temizliği. Güvenilir, referanslı personelimizle evinizin her köşesini pırıl pırıl yapıyoruz.',
    longDescription: 'Ev temizliği artık çok daha kolay. Deneyimli ve referanslı temizlik personelimizle evinizin derinlemesine temizliğini gerçekleştiriyoruz. Taşınma öncesi/sonrası, bayram temizliği veya periyodik temizlik için hemen randevu alabilirsiniz.',
    keywords: ['konut temizliği istanbul', 'ev temizliği istanbul', 'evde temizlik hizmeti', 'ev temizlik şirketi istanbul'],
    icon: 'home',
    category: 'ozel',
    benefits: [
      'Referanslı ve özgeçmişi kontrol edilmiş personel',
      'Esnek randevu saatleri',
      'Kendi temizlik malzemeleri ile hizmet',
      'Taşınma temizliği özel paketi',
      'Bayram ve özel gün temizliği',
      'Düzenli müşterilere özel indirim',
    ],
    process: [
      { step: 'Randevu', desc: 'Telefon veya WhatsApp ile uygun tarih belirleniyor.' },
      { step: 'Personel Atama', desc: 'Size en uygun deneyimli personel atanıyor.' },
      { step: 'Temizlik', desc: 'Sistematik ve detaylı temizlik yapılıyor.' },
      { step: 'Kontrol', desc: 'Temizlik sonrası memnuniyetiniz soruluyor.' },
    ],
    faq: [
      { q: 'Evde yokken temizlik yapabilir misiniz?', a: 'Evet, anahtarınızı güvenle bırakabilirsiniz. Personelimiz sigortalı ve referans kontrollüdür.' },
      { q: 'Temizlik malzemeleri kim tarafından temin ediliyor?', a: 'Tüm temizlik malzemeleri tarafımızca temin edilmektedir.' },
      { q: 'Kaç saatlik temizlik hizmeti alabiliyorum?', a: 'İhtiyacınıza göre 3 saatten başlayan esnek paketlerimiz bulunmaktadır.' },
    ],
  },
  {
    slug: 'villa-temizligi',
    title: 'Villa Temizliği İstanbul',
    shortTitle: 'Villa Temizliği',
    description: 'İstanbul ve çevresinde villa, müstakil ev ve rezidans temizliği. Büyük alanlara özel ekip ve ekipmanlarla detaylı temizlik hizmeti.',
    longDescription: 'Villalar ve büyük konutlar, standart daire temizliğinden çok daha kapsamlı bir hizmet gerektirir. Bahçe girişleri, havuz çevresi, geniş salonlar, çok katlı yapılar ve özel oda tasarımlarına uygun ekip ve ekipmanlarla villa temizliği sunuyoruz.',
    keywords: ['villa temizliği istanbul', 'villa temizlik hizmeti', 'müstakil ev temizliği', 'rezidans temizliği istanbul'],
    icon: 'villa',
    category: 'ozel',
    benefits: [
      'Büyük alanlara özel kalabalık ekip',
      'Havuz çevresi ve bahçe alanı temizliği',
      'Mermer ve özel zemin bakımı',
      'Kristal ve antika eşya dikkatli temizliği',
      'Aynı gün teslim hızlı servis',
      'Gizlilik ve özel müşteri protokolü',
    ],
    process: [
      { step: 'Villa İncelemesi', desc: 'Villanın büyüklüğü, oda sayısı ve özel alanlar belirleniyor.' },
      { step: 'Ekip Planlaması', desc: 'Villanın boyutuna göre uzman ekip belirleniyor.' },
      { step: 'Kapsamlı Temizlik', desc: 'Tüm kat ve bölümler sistematik olarak temizleniyor.' },
      { step: 'Final Denetim', desc: 'Her köşe kontrol edilip teslim yapılıyor.' },
    ],
    faq: [
      { q: 'Kaç kişilik ekip geliyor?', a: 'Villanın büyüklüğüne göre 4 ile 10 kişilik uzman ekip görevlendiriyoruz.' },
      { q: 'Antika ve özel eşyalar için ekstra dikkat gösteriyor musunuz?', a: 'Evet, değerli ve hassas eşyalar için özel eğitimli personel atıyoruz.' },
      { q: 'Havuz kenarı ve terası da temizliyor musunuz?', a: 'Evet, iç mekan yanı sıra teras, balkon ve bahçe alanları da hizmet kapsamımızdadır.' },
    ],
  },
  {
    slug: 'yazlik-temizligi',
    title: 'Yazlık Temizliği İstanbul ve Çevresi',
    shortTitle: 'Yazlık Temizliği',
    description: 'İstanbul çevresi ve Marmara bölgesinde yazlık, bungalov ve tatil evi temizliği. Sezonu açmadan önce veya kapatırken kapsamlı temizlik hizmeti.',
    longDescription: 'Uzun süre kullanılmayan yazlıklar, sezon öncesinde kapsamlı bir temizlik gerektirir. Nem, toz, mantar ve böceklerle başa çıkmak için özel ürünler ve teknikler kullanıyoruz. Yazlığınızı tatile başlamadan önce mükemmel şekilde hazırlıyoruz.',
    keywords: ['yazlık temizliği istanbul', 'tatil evi temizliği', 'yazlık açılış temizliği', 'bungalov temizliği'],
    icon: 'sun',
    category: 'ozel',
    benefits: [
      'Sezon açılış ve kapanış paketleri',
      'Nem ve küf giderme uzmanlaşması',
      'Havalandırma ve koku giderme',
      'Teras, balkon ve veranda temizliği',
      'Mobilya plastik örtü toplama ve düzenleme',
      'Uzak lokasyonlara ekip ulaşımı sağlanır',
    ],
    process: [
      { step: 'Sezon Değerlendirmesi', desc: 'Uzun süre boş kalan yazlığın durum tespiti yapılıyor.' },
      { step: 'Özel Plan', desc: 'Nem, toz ve koku durumuna göre özel temizlik planı.' },
      { step: 'Kapsamlı Temizlik', desc: 'Tüm mekan ve dış alanlar eksiksiz temizleniyor.' },
      { step: 'Hazır Teslim', desc: 'Yazlığınız tatile hazır şekilde teslim ediliyor.' },
    ],
    faq: [
      { q: 'Yazlığa uzak mesafeden ekip gönderebiliyor musunuz?', a: 'Evet, İstanbul dışındaki yakın lokasyonlara da ekip göndermek için iletişime geçebilirsiniz.' },
      { q: 'Nem ve küf problemi çözülebiliyor mu?', a: 'Evet, özel nem giderici ve antifungal ürünlerle yüzey ve iç ortam temizliği yapıyoruz.' },
      { q: 'Sezon sonunda kapatma temizliği de yapıyor musunuz?', a: 'Evet, sezon sonu kapama temizliği de hizmetlerimiz arasındadır.' },
    ],
  },
  /* ─── ENDÜSTRİ ─────────────────────────────────────────────── */
  {
    slug: 'insaat-sonrasi-temizlik',
    title: 'İnşaat Sonrası Temizlik İstanbul',
    shortTitle: 'İnşaat Sonrası Temizlik',
    description: 'İnşaat ve tadilat sonrası profesyonel temizlik. Kireç, alçı, boya izlerini eksiksiz temizleyip mekânınızı kullanıma hazır hale getiriyoruz.',
    longDescription: 'İnşaat sonrası temizlik, standart temizlikten çok farklı, uzmanlaşmış ekipman ve teknikler gerektiren bir hizmettir. Kireç lekeleri, alçı kalıntıları, boya izleri ve inşaat tozu gibi zorlu kirleri profesyonel ekibimizle tamamen temizliyoruz.',
    keywords: ['inşaat sonrası temizlik istanbul', 'tadilat sonrası temizlik', 'yapı temizliği', 'inşaat temizlik şirketi'],
    icon: 'hammer',
    category: 'endustri',
    benefits: [
      'Özel inşaat temizliği ekipmanları',
      'Kireç ve alçı izlerinin tamamen giderilmesi',
      'Pencere ve cam yüzeylerin detaylı temizliği',
      'Zemin polisaj ve koruma işlemleri',
      'Hızlı ve verimli çalışma',
      'Her büyüklükte proje için uygun',
    ],
    process: [
      { step: 'Saha Değerlendirmesi', desc: 'İnşaat alanı incelenerek temizlik kapsamı belirleniyor.' },
      { step: 'Kaba Temizlik', desc: 'İnşaat artıkları, ağır kirler ve döküntüler toplanıyor.' },
      { step: 'İnce Temizlik', desc: 'Yüzeyler, camlar ve detaylar özel ürünlerle temizleniyor.' },
      { step: 'Final Kontrol', desc: 'Mekân kullanıma hazır hale getirilip teslim ediliyor.' },
    ],
    faq: [
      { q: 'İnşaat sonrası temizlik ne kadar sürer?', a: 'Mekânın büyüklüğüne göre 1 günden birkaç güne kadar sürebilir.' },
      { q: 'Hangi yüzeyleri temizliyorsunuz?', a: 'Zemin, duvar, tavan, pencere, mutfak, banyo dahil tüm yüzeyleri temizliyoruz.' },
      { q: 'Fiyatlandırma nasıl yapılıyor?', a: 'Metrekare ve kirlilik düzeyine göre fiyat belirliyoruz. Ücretsiz keşif için arayabilirsiniz.' },
    ],
  },
  {
    slug: 'santiye-temizligi',
    title: 'Şantiye Temizliği İstanbul',
    shortTitle: 'Şantiye Temizliği',
    description: 'İstanbul\'da aktif şantiye ve inşaat alanı temizliği. Düzenli şantiye temizliği ile İSG standartlarına uyumlu çalışma ortamı sağlıyoruz.',
    longDescription: 'Aktif şantiye alanlarında temizlik hem zorunluluk hem de iş güvenliği gereğidir. Hafriyat artıkları, moloz, ambalaj malzemeleri ve toz kontrolü için düzenli şantiye temizliği hizmeti sunuyoruz. İSG mevzuatına uygun, güvenli çalışma ortamı oluşturuyoruz.',
    keywords: ['şantiye temizliği istanbul', 'inşaat alanı temizliği', 'moloz taşıma ve temizlik', 'aktif şantiye temizliği'],
    icon: 'hammer',
    category: 'endustri',
    benefits: [
      'Düzenli şantiye temizlik hizmeti',
      'Moloz ve artık malzeme taşıma',
      'Toz kontrol önlemleri',
      'İSG standartlarına uyumlu uygulama',
      'Farklı inşaat aşamalarına göre temizlik',
      'Şantiye konteyneri ve sosyal alan temizliği',
    ],
    process: [
      { step: 'Şantiye Briefi', desc: 'Proje büyüklüğü ve şantiye planı alınıyor.' },
      { step: 'Program', desc: 'İnşaat takvimine uyumlu temizlik programı hazırlanıyor.' },
      { step: 'Düzenli Temizlik', desc: 'Haftalık veya aylık programla şantiye temizleniyor.' },
      { step: 'Rapor', desc: 'Her temizlik kayıt altına alınıyor.' },
    ],
    faq: [
      { q: 'Şantiye temizliğini inşaat devam ederken yapıyor musunuz?', a: 'Evet, aktif inşaat çalışması devam ederken de güvenle temizlik yapabiliyoruz.' },
      { q: 'Moloz taşıma hizmeti de veriyor musunuz?', a: 'Evet, moloz ve inşaat artıklarının şantiyeden uzaklaştırılması da hizmetlerimiz arasındadır.' },
      { q: 'Şantiye tuvalet ve konteynerlerini de temizliyor musunuz?', a: 'Evet, sosyal alanlar ve konteynerler de temizlik kapsamında değerlendiriyoruz.' },
    ],
  },
  {
    slug: 'fabrika-temizligi',
    title: 'Fabrika Temizliği İstanbul',
    shortTitle: 'Fabrika Temizliği',
    description: 'İstanbul\'da endüstriyel fabrika temizliği. Üretim alanları, depo ve endüstriyel tesisler için özel ekipmanlarla profesyonel temizlik hizmeti.',
    longDescription: 'Fabrika ve endüstriyel tesis temizliği, özel ekipman ve uzmanlık gerektiren ayrı bir disiplindir. Yağ lekeleri, endüstriyel kirler ve makine çevresi temizliği konusunda deneyimli ekibimizle hizmet veriyoruz.',
    keywords: ['fabrika temizliği istanbul', 'endüstriyel temizlik', 'tesis temizliği istanbul', 'fabrika temizlik şirketi'],
    icon: 'factory',
    category: 'endustri',
    benefits: [
      'Endüstriyel güçlü temizlik ekipmanları',
      'Yağ ve endüstriyel kir uzmanlaşması',
      'Geniş alanlar için organize sistem',
      'İSG standartlarına uygunluk',
      'Üretimi aksatmayan program',
      'Periyodik bakım sözleşmeleri',
    ],
    process: [
      { step: 'Tesis Analizi', desc: 'Fabrika alanı ve temizlik ihtiyaçları analiz ediliyor.' },
      { step: 'Özel Program', desc: 'Üretime en az etki edecek temizlik takvimi oluşturuluyor.' },
      { step: 'Ekip Koordinasyonu', desc: 'Eğitimli endüstriyel temizlik ekibi sahada çalışıyor.' },
      { step: 'Denetim & Rapor', desc: 'Temizlik kalitesi denetleniyor, rapor sunuluyor.' },
    ],
    faq: [
      { q: 'Fabrika temizliği üretimi durduruyor mu?', a: 'Hayır. Üretim saatleri dışında veya bölüm bölüm temizlik yaparak sürekliliği sağlıyoruz.' },
      { q: 'Hangi endüstrilere hizmet veriyorsunuz?', a: 'Gıda, tekstil, metal, plastik ve pek çok endüstri koluna hizmet veriyoruz.' },
      { q: 'Ekipmanlar fabrika ortamına uygun mu?', a: 'Endüstriyel ortamlar için özel tasarlanmış güçlü ekipmanlar kullanıyoruz.' },
    ],
  },
  {
    slug: 'otel-temizligi',
    title: 'Otel Temizliği İstanbul',
    shortTitle: 'Otel Temizliği',
    description: 'İstanbul\'da 5 yıldız standartlarında otel ve konaklama tesisi temizliği. Oda, lobi, restoran ve ortak alanlar için profesyonel hizmet.',
    longDescription: 'Otel temizliği, konuk memnuniyeti ve hijyen standartları açısından son derece kritiktir. Eğitimli personelimizle otel odaları, lobiler, restoranlar ve tüm ortak alanlarda uluslararası standartlarda temizlik hizmeti sunuyoruz.',
    keywords: ['otel temizliği istanbul', 'konaklama tesisi temizliği', 'otel temizlik şirketi', 'hospitality temizlik'],
    icon: 'hotel',
    category: 'kurumsal',
    benefits: [
      'Uluslararası otel standartlarına uygun hizmet',
      'Check-in/check-out programına uyum',
      'Oda temizliği, banyo hijyeni',
      'Lobi, restoran, ortak alan temizliği',
      'Hızlı oda devir teslimi',
      'Gizlilik ve güvenlik protokolleri',
    ],
    process: [
      { step: 'Standart Belirleme', desc: 'Otelinizin temizlik standartları belirleniyor.' },
      { step: 'Ekip Eğitimi', desc: 'Personel otelinizin özel gereksinimlerine göre eğitiliyor.' },
      { step: 'Günlük Operasyon', desc: 'Odalar ve ortak alanlar plana göre temizleniyor.' },
      { step: 'Kalite Denetimi', desc: 'Süpervizör kontrolüyle her temizlik onaylanıyor.' },
    ],
    faq: [
      { q: 'Dışarıdan temizlik şirketi ile çalışmak güvenli mi?', a: 'Personelimiz SGK\'lı, sigortalı ve referans kontrollü. Güvenilirlik önceliğimizdir.' },
      { q: 'Mevsimsel yoğunluğa göre kadro ayarlanabilir mi?', a: 'Evet, sezonluk ihtiyacınıza göre esnek kadro planlaması yapabiliyoruz.' },
      { q: 'Otel restoranı ve mutfak temizliği yapıyor musunuz?', a: 'Evet, mutfak ve restoran temizliği de hizmet kapsamımızdadır.' },
    ],
  },
  {
    slug: 'dis-cephe-cam-temizligi',
    title: 'Dış Cephe Cam Temizliği İstanbul',
    shortTitle: 'Dış Cephe Cam Temizliği',
    description: 'İstanbul\'da yüksek bina dış cephe ve cam temizliği. Rope access ve platform sistemleriyle İSG sertifikalı uzmanlar tarafından güvenli cam temizliği.',
    longDescription: 'Dış cephe cam temizliği özellikle yüksek katlı binalarda uzmanlık ve özel ekipman gerektiren tehlikeli bir iştir. Rope access (halatlı erişim) ve platform sistemleriyle bina dış cephe cam temizliğini güvenle gerçekleştiriyoruz.',
    keywords: ['dış cephe cam temizliği istanbul', 'bina cam temizliği', 'yüksek bina cam temizliği', 'rope access cam temizliği'],
    icon: 'window',
    category: 'endustri',
    benefits: [
      'İSG sertifikalı yüksek erişim uzmanları',
      'Rope access ve platform sistemleri',
      'Damlasız cam temizleme teknolojisi',
      'İç ve dış cam yüzeyleri',
      'Periyodik bakım sözleşmesi imkânı',
      'Sigortalı operasyon',
    ],
    process: [
      { step: 'Teknik Değerlendirme', desc: 'Bina yüksekliği ve erişim yöntemi belirleniyor.' },
      { step: 'Güvenlik Planı', desc: 'İSG standartlarına uygun çalışma planı hazırlanıyor.' },
      { step: 'Profesyonel Uygulama', desc: 'Sertifikalı uzmanlar cam temizliğini yapıyor.' },
      { step: 'Kalite Kontrolü', desc: 'Tüm yüzeyler kontrol edilerek onaylanıyor.' },
    ],
    faq: [
      { q: 'Yüksek katlı binalarda cam temizliği yapabiliyor musunuz?', a: 'Evet, rope access uzmanlarımızla yüksek katlı binalarda güvenle çalışıyoruz.' },
      { q: 'Cam temizliği ne sıklıkla yapılmalıdır?', a: 'İstanbul\'un hava koşulları göz önünde bulundurulduğunda 2-3 ayda bir önerilir.' },
      { q: 'Hava koşullarına göre temizlik erteleniyor mu?', a: 'Rüzgarlı ve yağışlı havalarda güvenlik nedeniyle çalışmıyoruz.' },
    ],
  },
]

export function getServiceBySlug(slug: string): Service | undefined {
  return services.find((s) => s.slug === slug)
}

export function getServicesByCategory(category: Service['category']): Service[] {
  return services.filter((s) => s.category === category)
}
